# Generated by Django 3.2.4 on 2021-06-17 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('subid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_ins', models.CharField(max_length=300)),
                ('dba_name', models.CharField(blank=True, max_length=300)),
                ('m_street_addy', models.CharField(max_length=120)),
                ('m_street_2_addy', models.CharField(blank=True, max_length=80)),
                ('m_city', models.CharField(max_length=35)),
                ('m_zip', models.IntegerField()),
                ('m_state', models.CharField(max_length=2)),
                ('p_street_addy', models.CharField(max_length=120)),
                ('p_street_2_addy', models.CharField(blank=True, max_length=80)),
                ('p_city', models.CharField(max_length=35)),
                ('p_zip', models.IntegerField()),
                ('p_state', models.CharField(max_length=2)),
                ('eff_date', models.DateField(default=datetime.date.today)),
                ('lob', models.CharField(max_length=40)),
                ('policy_num', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
